In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Colab Notebooks/Social_Network_Ads.csv')

In [3]:
df

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [5]:
X = df.iloc[:,:-1].values

In [6]:
y = df.iloc[:,-1].values

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
sc = StandardScaler()

In [12]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
classifier = LogisticRegression(random_state=0)

In [15]:
classifier.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [16]:
print(X_test)

[[3.00e+01 8.70e+04]
 [3.80e+01 5.00e+04]
 [3.50e+01 7.50e+04]
 [3.00e+01 7.90e+04]
 [3.50e+01 5.00e+04]
 [2.70e+01 2.00e+04]
 [3.10e+01 1.50e+04]
 [3.60e+01 1.44e+05]
 [1.80e+01 6.80e+04]
 [4.70e+01 4.30e+04]
 [3.00e+01 4.90e+04]
 [2.80e+01 5.50e+04]
 [3.70e+01 5.50e+04]
 [3.90e+01 7.70e+04]
 [2.00e+01 8.60e+04]
 [3.20e+01 1.17e+05]
 [3.70e+01 7.70e+04]
 [1.90e+01 8.50e+04]
 [5.50e+01 1.30e+05]
 [3.50e+01 2.20e+04]
 [3.50e+01 4.70e+04]
 [4.70e+01 1.44e+05]
 [4.10e+01 5.10e+04]
 [4.70e+01 1.05e+05]
 [2.30e+01 2.80e+04]
 [4.90e+01 1.41e+05]
 [2.80e+01 8.70e+04]
 [2.90e+01 8.00e+04]
 [3.70e+01 6.20e+04]
 [3.20e+01 8.60e+04]
 [2.10e+01 8.80e+04]
 [3.70e+01 7.90e+04]
 [5.70e+01 6.00e+04]
 [3.70e+01 5.30e+04]
 [2.40e+01 5.80e+04]
 [1.80e+01 5.20e+04]
 [2.20e+01 8.10e+04]
 [3.40e+01 4.30e+04]
 [3.10e+01 3.40e+04]
 [4.90e+01 3.60e+04]
 [2.70e+01 8.80e+04]
 [4.10e+01 5.20e+04]
 [2.70e+01 8.40e+04]
 [3.50e+01 2.00e+04]
 [4.30e+01 1.12e+05]
 [2.70e+01 5.80e+04]
 [3.70e+01 8.00e+04]
 [5.20e+01 9.

In [17]:
print(classifier.predict(sc.transform([[35,41000]])))

[1]


In [18]:
print(classifier.predict(sc.transform([[45,85000]])))

[1]


In [19]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]]


In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [21]:
cm = confusion_matrix(y_test,y_pred)

In [22]:
print(cm)

[[ 0 68]
 [ 0 32]]


In [23]:
accuracy_score(y_test,y_pred)

0.32